default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 5000
  username: postgres          # Add your PostgreSQL username here
  password: Dublin247$

development:
  <<: *default
  database: counciltracker2024

test:
  <<: *default
  database: counciltracker_test

production:
  <<: *default
  database: counciltracker_production
  username: postgres
  password: Dublin247$